## 📚

In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Data.xlsx")

In [3]:
df

       Name  Math  Science  SST  Hindi  English
0     Raman    61       97   97     37       59
1     Kamal    82       23   91     71       97
2    Subham    79       16   35     88       76
3     Komal     2        8   28     12        5
4     Madan     9       14   74     63       15
5     Rahul    35       94   90     98       68
6     Sumit    43       38    7     48       74
7   Kashish    15       43   38     29       28
8      Raju    47       17   22     50       72
9    Gungun    53       88   64     51        5
10   Gungun    53       88   64     51        5
11   Subham    79       16   35     88       76

In [4]:
# If the column name is already available then it will update otherwise it will create new column
# axis=1 means horizontal
# axis=0 means vertical
# numeric_only=True will make sure only numerical columns will be considered and ignore non-numerical columns
df["Total"]=df.sum(axis=1, numeric_only=True)

In [5]:
df

       Name  Math  Science  SST  Hindi  English  Total
0     Raman    61       97   97     37       59    351
1     Kamal    82       23   91     71       97    364
2    Subham    79       16   35     88       76    294
3     Komal     2        8   28     12        5     55
4     Madan     9       14   74     63       15    175
5     Rahul    35       94   90     98       68    385
6     Sumit    43       38    7     48       74    210
7   Kashish    15       43   38     29       28    153
8      Raju    47       17   22     50       72    208
9    Gungun    53       88   64     51        5    261
10   Gungun    53       88   64     51        5    261
11   Subham    79       16   35     88       76    294

In [6]:
# if we want to create a new column then we can simply divide the total by number of subjects
df["Average"]=df["Total"]/5

In [7]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average
0     Raman    61       97   97     37       59    351     70.2
1     Kamal    82       23   91     71       97    364     72.8
2    Subham    79       16   35     88       76    294     58.8
3     Komal     2        8   28     12        5     55     11.0
4     Madan     9       14   74     63       15    175     35.0
5     Rahul    35       94   90     98       68    385     77.0
6     Sumit    43       38    7     48       74    210     42.0
7   Kashish    15       43   38     29       28    153     30.6
8      Raju    47       17   22     50       72    208     41.6
9    Gungun    53       88   64     51        5    261     52.2
10   Gungun    53       88   64     51        5    261     52.2
11   Subham    79       16   35     88       76    294     58.8

In [8]:
# if we run the cell and it doesn't show the result instantly that means it updated it in the original DataFrame.
# otherwise we have to mention inplace=True to update the original DataFrame.

df.drop(columns=["Total", "Average"], inplace=True)

In [9]:
df

       Name  Math  Science  SST  Hindi  English
0     Raman    61       97   97     37       59
1     Kamal    82       23   91     71       97
2    Subham    79       16   35     88       76
3     Komal     2        8   28     12        5
4     Madan     9       14   74     63       15
5     Rahul    35       94   90     98       68
6     Sumit    43       38    7     48       74
7   Kashish    15       43   38     29       28
8      Raju    47       17   22     50       72
9    Gungun    53       88   64     51        5
10   Gungun    53       88   64     51        5
11   Subham    79       16   35     88       76

In [10]:
# now suppose if we just want the total of Maths, Science and English.

df["MSE"]=df["Math"]+df["Science"]+df["English"]

In [11]:
df

       Name  Math  Science  SST  Hindi  English  MSE
0     Raman    61       97   97     37       59  217
1     Kamal    82       23   91     71       97  202
2    Subham    79       16   35     88       76  171
3     Komal     2        8   28     12        5   15
4     Madan     9       14   74     63       15   38
5     Rahul    35       94   90     98       68  197
6     Sumit    43       38    7     48       74  155
7   Kashish    15       43   38     29       28   86
8      Raju    47       17   22     50       72  136
9    Gungun    53       88   64     51        5  146
10   Gungun    53       88   64     51        5  146
11   Subham    79       16   35     88       76  171

In [12]:
# to drop column
df.drop(columns="MSE", inplace=True)

In [13]:
df

       Name  Math  Science  SST  Hindi  English
0     Raman    61       97   97     37       59
1     Kamal    82       23   91     71       97
2    Subham    79       16   35     88       76
3     Komal     2        8   28     12        5
4     Madan     9       14   74     63       15
5     Rahul    35       94   90     98       68
6     Sumit    43       38    7     48       74
7   Kashish    15       43   38     29       28
8      Raju    47       17   22     50       72
9    Gungun    53       88   64     51        5
10   Gungun    53       88   64     51        5
11   Subham    79       16   35     88       76

In [14]:
# now we want subject-wise total
# if we want mention numeric_only=True, it will concat the strings along with it.

df.loc["Total"]=df.sum(axis=0)

In [15]:
df

,Name,Math,Science,SST,Hindi,English
0,Raman,61,97,97,37,59
1,Kamal,82,23,91,71,97
2,Subham,79,16,35,88,76
3,Komal,2,8,28,12,5
4,Madan,9,14,74,63,15
5,Rahul,35,94,90,98,68
6,Sumit,43,38,7,48,74
7,Kashish,15,43,38,29,28
8,Raju,47,17,22,50,72
9,Gungun,53,88,64,51,5
10,Gungun,53,88,64,51,5
11,Subham,79,16,35,88,76
Total,RamanKamalSubhamKomalMadanRahulSumitKashishRaj...,558,542,645,686,580

In [16]:
df.drop("Total", inplace=True)

In [17]:
df

       Name  Math  Science  SST  Hindi  English
0     Raman    61       97   97     37       59
1     Kamal    82       23   91     71       97
2    Subham    79       16   35     88       76
3     Komal     2        8   28     12        5
4     Madan     9       14   74     63       15
5     Rahul    35       94   90     98       68
6     Sumit    43       38    7     48       74
7   Kashish    15       43   38     29       28
8      Raju    47       17   22     50       72
9    Gungun    53       88   64     51        5
10   Gungun    53       88   64     51        5
11   Subham    79       16   35     88       76

In [18]:
df.loc["Total"]=df.sum(axis=0, numeric_only=True)

In [19]:
df

          Name   Math  Science    SST  Hindi  English
0        Raman   61.0     97.0   97.0   37.0     59.0
1        Kamal   82.0     23.0   91.0   71.0     97.0
2       Subham   79.0     16.0   35.0   88.0     76.0
3        Komal    2.0      8.0   28.0   12.0      5.0
4        Madan    9.0     14.0   74.0   63.0     15.0
5        Rahul   35.0     94.0   90.0   98.0     68.0
6        Sumit   43.0     38.0    7.0   48.0     74.0
7      Kashish   15.0     43.0   38.0   29.0     28.0
8         Raju   47.0     17.0   22.0   50.0     72.0
9       Gungun   53.0     88.0   64.0   51.0      5.0
10      Gungun   53.0     88.0   64.0   51.0      5.0
11      Subham   79.0     16.0   35.0   88.0     76.0
Total      NaN  558.0    542.0  645.0  686.0    580.0

In [20]:
# to rename columns we have rename method and we define it in dictionary
# now suppose we want weekdays intead of subjects

df.rename(columns={"Math": "Monday", "Science": "Tuesday", "SST": "Wednesday", "Hindi": "Thursday", "English": "Friday"}, inplace=True)

In [21]:
df

          Name  Monday  Tuesday  Wednesday  Thursday  Friday
0        Raman    61.0     97.0       97.0      37.0    59.0
1        Kamal    82.0     23.0       91.0      71.0    97.0
2       Subham    79.0     16.0       35.0      88.0    76.0
3        Komal     2.0      8.0       28.0      12.0     5.0
4        Madan     9.0     14.0       74.0      63.0    15.0
5        Rahul    35.0     94.0       90.0      98.0    68.0
6        Sumit    43.0     38.0        7.0      48.0    74.0
7      Kashish    15.0     43.0       38.0      29.0    28.0
8         Raju    47.0     17.0       22.0      50.0    72.0
9       Gungun    53.0     88.0       64.0      51.0     5.0
10      Gungun    53.0     88.0       64.0      51.0     5.0
11      Subham    79.0     16.0       35.0      88.0    76.0
Total      NaN   558.0    542.0      645.0     686.0   580.0

In [22]:
df.drop("Total", inplace=True)

In [23]:
# add(), sub(), mul(), div()

In [24]:
# suppose these are the weekly sales of each employee in usd and we want that in INR
# we can simply multiply it by 95 to get the sales in INR.

# but first we have to separate the numerical and non-numerical columns.

df_name=df.iloc[:,:1]

In [25]:
df_name

       Name
0     Raman
1     Kamal
2    Subham
3     Komal
4     Madan
5     Rahul
6     Sumit
7   Kashish
8      Raju
9    Gungun
10   Gungun
11   Subham

In [26]:
df_data=df.iloc[:,1:]

In [27]:
df_data

    Monday  Tuesday  Wednesday  Thursday  Friday
0     61.0     97.0       97.0      37.0    59.0
1     82.0     23.0       91.0      71.0    97.0
2     79.0     16.0       35.0      88.0    76.0
3      2.0      8.0       28.0      12.0     5.0
4      9.0     14.0       74.0      63.0    15.0
5     35.0     94.0       90.0      98.0    68.0
6     43.0     38.0        7.0      48.0    74.0
7     15.0     43.0       38.0      29.0    28.0
8     47.0     17.0       22.0      50.0    72.0
9     53.0     88.0       64.0      51.0     5.0
10    53.0     88.0       64.0      51.0     5.0
11    79.0     16.0       35.0      88.0    76.0

In [28]:
df_data=df_data.mul(95)

In [29]:
df_data

    Monday  Tuesday  Wednesday  Thursday  Friday
0   5795.0   9215.0     9215.0    3515.0  5605.0
1   7790.0   2185.0     8645.0    6745.0  9215.0
2   7505.0   1520.0     3325.0    8360.0  7220.0
3    190.0    760.0     2660.0    1140.0   475.0
4    855.0   1330.0     7030.0    5985.0  1425.0
5   3325.0   8930.0     8550.0    9310.0  6460.0
6   4085.0   3610.0      665.0    4560.0  7030.0
7   1425.0   4085.0     3610.0    2755.0  2660.0
8   4465.0   1615.0     2090.0    4750.0  6840.0
9   5035.0   8360.0     6080.0    4845.0   475.0
10  5035.0   8360.0     6080.0    4845.0   475.0
11  7505.0   1520.0     3325.0    8360.0  7220.0

In [30]:
df=df_name.join(df_data)

In [31]:
df

       Name  Monday  Tuesday  Wednesday  Thursday  Friday
0     Raman  5795.0   9215.0     9215.0    3515.0  5605.0
1     Kamal  7790.0   2185.0     8645.0    6745.0  9215.0
2    Subham  7505.0   1520.0     3325.0    8360.0  7220.0
3     Komal   190.0    760.0     2660.0    1140.0   475.0
4     Madan   855.0   1330.0     7030.0    5985.0  1425.0
5     Rahul  3325.0   8930.0     8550.0    9310.0  6460.0
6     Sumit  4085.0   3610.0      665.0    4560.0  7030.0
7   Kashish  1425.0   4085.0     3610.0    2755.0  2660.0
8      Raju  4465.0   1615.0     2090.0    4750.0  6840.0
9    Gungun  5035.0   8360.0     6080.0    4845.0   475.0
10   Gungun  5035.0   8360.0     6080.0    4845.0   475.0
11   Subham  7505.0   1520.0     3325.0    8360.0  7220.0

In [32]:
# now we have to add one more column of pass/fail in the original DataFrame

df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Data.xlsx")

In [33]:
df

       Name  Math  Science  SST  Hindi  English
0     Raman    61       97   97     37       59
1     Kamal    82       23   91     71       97
2    Subham    79       16   35     88       76
3     Komal     2        8   28     12        5
4     Madan     9       14   74     63       15
5     Rahul    35       94   90     98       68
6     Sumit    43       38    7     48       74
7   Kashish    15       43   38     29       28
8      Raju    47       17   22     50       72
9    Gungun    53       88   64     51        5
10   Gungun    53       88   64     51        5
11   Subham    79       16   35     88       76

In [34]:
df["Total"]=df.sum(axis=1, numeric_only=True)

In [35]:
df

       Name  Math  Science  SST  Hindi  English  Total
0     Raman    61       97   97     37       59    351
1     Kamal    82       23   91     71       97    364
2    Subham    79       16   35     88       76    294
3     Komal     2        8   28     12        5     55
4     Madan     9       14   74     63       15    175
5     Rahul    35       94   90     98       68    385
6     Sumit    43       38    7     48       74    210
7   Kashish    15       43   38     29       28    153
8      Raju    47       17   22     50       72    208
9    Gungun    53       88   64     51        5    261
10   Gungun    53       88   64     51        5    261
11   Subham    79       16   35     88       76    294

In [36]:
df["Average"]=df["Total"]/5

In [37]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average
0     Raman    61       97   97     37       59    351     70.2
1     Kamal    82       23   91     71       97    364     72.8
2    Subham    79       16   35     88       76    294     58.8
3     Komal     2        8   28     12        5     55     11.0
4     Madan     9       14   74     63       15    175     35.0
5     Rahul    35       94   90     98       68    385     77.0
6     Sumit    43       38    7     48       74    210     42.0
7   Kashish    15       43   38     29       28    153     30.6
8      Raju    47       17   22     50       72    208     41.6
9    Gungun    53       88   64     51        5    261     52.2
10   Gungun    53       88   64     51        5    261     52.2
11   Subham    79       16   35     88       76    294     58.8

In [38]:
# if the average is above 40 then the student is pass otherswise fail
# Method-1:

l=["Pass" if i>40 else "Fail" for i in df["Average"]]

In [39]:
df["Pass/Fail"]=l

In [40]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average Pass/Fail
0     Raman    61       97   97     37       59    351     70.2      Pass
1     Kamal    82       23   91     71       97    364     72.8      Pass
2    Subham    79       16   35     88       76    294     58.8      Pass
3     Komal     2        8   28     12        5     55     11.0      Fail
4     Madan     9       14   74     63       15    175     35.0      Fail
5     Rahul    35       94   90     98       68    385     77.0      Pass
6     Sumit    43       38    7     48       74    210     42.0      Pass
7   Kashish    15       43   38     29       28    153     30.6      Fail
8      Raju    47       17   22     50       72    208     41.6      Pass
9    Gungun    53       88   64     51        5    261     52.2      Pass
10   Gungun    53       88   64     51        5    261     52.2      Pass
11   Subham    79       16   35     88       76    294     58.8      Pass

In [41]:
df.drop(columns="Pass/Fail", inplace=True)

In [42]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average
0     Raman    61       97   97     37       59    351     70.2
1     Kamal    82       23   91     71       97    364     72.8
2    Subham    79       16   35     88       76    294     58.8
3     Komal     2        8   28     12        5     55     11.0
4     Madan     9       14   74     63       15    175     35.0
5     Rahul    35       94   90     98       68    385     77.0
6     Sumit    43       38    7     48       74    210     42.0
7   Kashish    15       43   38     29       28    153     30.6
8      Raju    47       17   22     50       72    208     41.6
9    Gungun    53       88   64     51        5    261     52.2
10   Gungun    53       88   64     51        5    261     52.2
11   Subham    79       16   35     88       76    294     58.8

In [43]:
# Method-2: by using apply method, it will automatically apply that function to each row at that column

def check(x):
    if x>40:
        return "Pass"
    else:
        return "Fail"

In [44]:
df["Pass/Fail"]=df.Average.apply(check)

In [45]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average Pass/Fail
0     Raman    61       97   97     37       59    351     70.2      Pass
1     Kamal    82       23   91     71       97    364     72.8      Pass
2    Subham    79       16   35     88       76    294     58.8      Pass
3     Komal     2        8   28     12        5     55     11.0      Fail
4     Madan     9       14   74     63       15    175     35.0      Fail
5     Rahul    35       94   90     98       68    385     77.0      Pass
6     Sumit    43       38    7     48       74    210     42.0      Pass
7   Kashish    15       43   38     29       28    153     30.6      Fail
8      Raju    47       17   22     50       72    208     41.6      Pass
9    Gungun    53       88   64     51        5    261     52.2      Pass
10   Gungun    53       88   64     51        5    261     52.2      Pass
11   Subham    79       16   35     88       76    294     58.8      Pass

In [46]:
# now suppose student will be passed only if all the subjects marks are above 40. otherwise fail.

df.drop(columns="Pass/Fail", inplace=True)

In [47]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average
0     Raman    61       97   97     37       59    351     70.2
1     Kamal    82       23   91     71       97    364     72.8
2    Subham    79       16   35     88       76    294     58.8
3     Komal     2        8   28     12        5     55     11.0
4     Madan     9       14   74     63       15    175     35.0
5     Rahul    35       94   90     98       68    385     77.0
6     Sumit    43       38    7     48       74    210     42.0
7   Kashish    15       43   38     29       28    153     30.6
8      Raju    47       17   22     50       72    208     41.6
9    Gungun    53       88   64     51        5    261     52.2
10   Gungun    53       88   64     51        5    261     52.2
11   Subham    79       16   35     88       76    294     58.8

In [50]:
def check1(x):
    if x["Math"]>=40 and x["Science"]>=40 and x["SST"]>=40 and x["Hindi"]>=40 and x["English"]>=40:
        return "Pass"
    else:
        return "Fail"

In [52]:
df["Pass/Fail"]=df.apply(check1, axis=1)

In [53]:
df

       Name  Math  Science  SST  Hindi  English  Total  Average Pass/Fail
0     Raman    61       97   97     37       59    351     70.2      Fail
1     Kamal    82       23   91     71       97    364     72.8      Fail
2    Subham    79       16   35     88       76    294     58.8      Fail
3     Komal     2        8   28     12        5     55     11.0      Fail
4     Madan     9       14   74     63       15    175     35.0      Fail
5     Rahul    35       94   90     98       68    385     77.0      Fail
6     Sumit    43       38    7     48       74    210     42.0      Fail
7   Kashish    15       43   38     29       28    153     30.6      Fail
8      Raju    47       17   22     50       72    208     41.6      Fail
9    Gungun    53       88   64     51        5    261     52.2      Fail
10   Gungun    53       88   64     51        5    261     52.2      Fail
11   Subham    79       16   35     88       76    294     58.8      Fail