## 📚 Handling Null Values

In [2]:
import pandas as pd

In [96]:
df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\NAData.xlsx")

In [97]:
df

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0      NaN  32.0
2  Subham   NaN       69   69.0      NaN  40.0
3  Shayam   NaN       21    NaN     80.0  34.0
4   Gopal   NaN       64   55.0      5.0  98.0
5   Rohit  17.0       37    NaN     72.0   NaN
6   Bhola  96.0       13   82.0     15.0   NaN
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35    NaN      1.0  87.0

In [5]:
df.isnull()

    Name   Math  Science  Hindi  English    SST
0  False  False    False  False    False  False
1  False  False    False  False     True  False
2  False   True    False  False     True  False
3  False   True    False   True    False  False
4  False   True    False  False    False  False
5  False  False    False   True    False   True
6  False  False    False  False    False   True
7  False  False    False  False    False  False
8  False  False    False  False    False  False
9  False  False    False   True    False  False

In [9]:
# so true is 1 and false is 0. if we sum the true we will get the total number of null values in that column
# Null values is blank columns
df.isnull().sum()

Name       0
Math       3
Science    0
Hindi      3
English    2
SST        2
dtype: int64

In [11]:
# 1. We can drop the rows having null values
df.dropna()

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0

In [13]:
# dropna method has argument thresh which means how many non-null values are allowed in a row.

df.dropna(thresh=5) # thresh=5 means it should have minimum 5 non-null values in a row if it's less it will drop that row

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0      NaN  32.0
4   Gopal   NaN       64   55.0      5.0  98.0
6   Bhola  96.0       13   82.0     15.0   NaN
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35    NaN      1.0  87.0

In [15]:
# to run it columns-wise just try changing the axis

df.dropna(axis=1, thresh=8) # if there is less than 8 non-null values it will drop that column

     Name  Science  English   SST
0  Mayank       46     71.0  14.0
1  Gungun       54      NaN  32.0
2  Subham       69      NaN  40.0
3  Shayam       21     80.0  34.0
4   Gopal       64      5.0  98.0
5   Rohit       37     72.0   NaN
6   Bhola       13     15.0   NaN
7    Golu       96      9.0  60.0
8   Nayan       21     58.0  33.0
9   Kamal       35      1.0  87.0

In [17]:
# we can replace the null value with a particular value

df.fillna(40) # this will replace all the null values with the assigned value

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0     40.0  32.0
2  Subham  40.0       69   69.0     40.0  40.0
3  Shayam  40.0       21   40.0     80.0  34.0
4   Gopal  40.0       64   55.0      5.0  98.0
5   Rohit  17.0       37   40.0     72.0  40.0
6   Bhola  96.0       13   82.0     15.0  40.0
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35   40.0      1.0  87.0

In [20]:
df

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0      NaN  32.0
2  Subham   NaN       69   69.0      NaN  40.0
3  Shayam   NaN       21    NaN     80.0  34.0
4   Gopal   NaN       64   55.0      5.0  98.0
5   Rohit  17.0       37    NaN     72.0   NaN
6   Bhola  96.0       13   82.0     15.0   NaN
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35    NaN      1.0  87.0

In [19]:
# we can also pass a dictionary to mention particular value for particular column

df.fillna({"Math": 40, "Hindi": 30})

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0      NaN  32.0
2  Subham  40.0       69   69.0      NaN  40.0
3  Shayam  40.0       21   30.0     80.0  34.0
4   Gopal  40.0       64   55.0      5.0  98.0
5   Rohit  17.0       37   30.0     72.0   NaN
6   Bhola  96.0       13   82.0     15.0   NaN
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35   30.0      1.0  87.0

In [23]:
# so mean method generally gives the mean for that particular column
# use numeric_only=True to avoid string columns
df.mean(numeric_only=True)

Math       61.428571
Science    45.600000
Hindi      52.000000
English    38.875000
SST        49.750000
dtype: float64

In [25]:
df.fillna(df.mean(numeric_only=True)) # this will replace null with mean of that column

     Name       Math  Science  Hindi  English    SST
0  Mayank  62.000000       46   53.0   71.000  14.00
1  Gungun  91.000000       54   52.0   38.875  32.00
2  Subham  61.428571       69   69.0   38.875  40.00
3  Shayam  61.428571       21   52.0   80.000  34.00
4   Gopal  61.428571       64   55.0    5.000  98.00
5   Rohit  17.000000       37   52.0   72.000  49.75
6   Bhola  96.000000       13   82.0   15.000  49.75
7    Golu   9.000000       96   35.0    9.000  60.00
8   Nayan  65.000000       21   18.0   58.000  33.00
9   Kamal  90.000000       35   52.0    1.000  87.00

In [26]:
# so there are two separate methods which are used to handle null values
# first one is ffill and the other one is bfill

df.ffill()

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0     71.0  32.0
2  Subham  91.0       69   69.0     71.0  40.0
3  Shayam  91.0       21   69.0     80.0  34.0
4   Gopal  91.0       64   55.0      5.0  98.0
5   Rohit  17.0       37   55.0     72.0  98.0
6   Bhola  96.0       13   82.0     15.0  98.0
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35   18.0      1.0  87.0

In [27]:
df.bfill()

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0     80.0  32.0
2  Subham  17.0       69   69.0     80.0  40.0
3  Shayam  17.0       21   55.0     80.0  34.0
4   Gopal  17.0       64   55.0      5.0  98.0
5   Rohit  17.0       37   82.0     72.0  60.0
6   Bhola  96.0       13   82.0     15.0  60.0
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35    NaN      1.0  87.0

In [28]:
# to change it to row-wise instead of column change the axis
df.ffill(axis=1)

     Name    Math Science Hindi English   SST
0  Mayank    62.0      46  53.0    71.0  14.0
1  Gungun    91.0      54  52.0    52.0  32.0
2  Subham  Subham      69  69.0    69.0  40.0
3  Shayam  Shayam      21    21    80.0  34.0
4   Gopal   Gopal      64  55.0     5.0  98.0
5   Rohit    17.0      37    37    72.0  72.0
6   Bhola    96.0      13  82.0    15.0  15.0
7    Golu     9.0      96  35.0     9.0  60.0
8   Nayan    65.0      21  18.0    58.0  33.0
9   Kamal    90.0      35    35     1.0  87.0

In [29]:
# can keep the limit to repeat the same value to a particular limit

df.ffill(limit=2)

     Name  Math  Science  Hindi  English   SST
0  Mayank  62.0       46   53.0     71.0  14.0
1  Gungun  91.0       54   52.0     71.0  32.0
2  Subham  91.0       69   69.0     71.0  40.0
3  Shayam  91.0       21   69.0     80.0  34.0
4   Gopal   NaN       64   55.0      5.0  98.0
5   Rohit  17.0       37   55.0     72.0  98.0
6   Bhola  96.0       13   82.0     15.0  98.0
7    Golu   9.0       96   35.0      9.0  60.0
8   Nayan  65.0       21   18.0     58.0  33.0
9   Kamal  90.0       35   18.0      1.0  87.0

In [103]:
df=df.iloc[:,1:]

In [104]:
df

   Math  Science  Hindi  English   SST
0  62.0       46   53.0     71.0  14.0
1  91.0       54   52.0      NaN  32.0
2   NaN       69   69.0      NaN  40.0
3   NaN       21    NaN     80.0  34.0
4   NaN       64   55.0      5.0  98.0
5  17.0       37    NaN     72.0   NaN
6  96.0       13   82.0     15.0   NaN
7   9.0       96   35.0      9.0  60.0
8  65.0       21   18.0     58.0  33.0
9  90.0       35    NaN      1.0  87.0

In [105]:
# in pandas interpolate() is a method which fills the null values on the basis of the surrounding data points instead of a fixed constant value

df.interpolate()

   Math  Science  Hindi  English        SST
0  62.0       46   53.0     71.0  14.000000
1  91.0       54   52.0     74.0  32.000000
2  72.5       69   69.0     77.0  40.000000
3  54.0       21   62.0     80.0  34.000000
4  35.5       64   55.0      5.0  98.000000
5  17.0       37   68.5     72.0  85.333333
6  96.0       13   82.0     15.0  72.666667
7   9.0       96   35.0      9.0  60.000000
8  65.0       21   18.0     58.0  33.000000
9  90.0       35   18.0      1.0  87.000000

In [39]:
df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Sample - Superstore.xls")
pd.options.display.max_columns=50

In [40]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [41]:
# as of now we are just taking 10 rows and 3 columns["Customer Name", "Segment", "Country"]

df=df.loc[5:15,["Customer Name", "Segment", "Country"]]

In [42]:
df

      Customer Name      Segment        Country
5   Brosina Hoffman     Consumer  United States
6   Brosina Hoffman     Consumer  United States
7   Brosina Hoffman     Consumer  United States
8   Brosina Hoffman     Consumer  United States
9   Brosina Hoffman     Consumer  United States
10  Brosina Hoffman     Consumer  United States
11  Brosina Hoffman     Consumer  United States
12     Andrew Allen     Consumer  United States
13     Irene Maddox     Consumer  United States
14    Harold Pawlan  Home Office  United States
15    Harold Pawlan  Home Office  United States

In [44]:
# whenever we want to use python string method we just have to use .str then the method name
# now here suppose we have to make customer name upper case

df["Customer Name"]=df["Customer Name"].str.upper()

In [45]:
df

      Customer Name      Segment        Country
5   BROSINA HOFFMAN     Consumer  United States
6   BROSINA HOFFMAN     Consumer  United States
7   BROSINA HOFFMAN     Consumer  United States
8   BROSINA HOFFMAN     Consumer  United States
9   BROSINA HOFFMAN     Consumer  United States
10  BROSINA HOFFMAN     Consumer  United States
11  BROSINA HOFFMAN     Consumer  United States
12     ANDREW ALLEN     Consumer  United States
13     IRENE MADDOX     Consumer  United States
14    HAROLD PAWLAN  Home Office  United States
15    HAROLD PAWLAN  Home Office  United States

In [46]:
# we have to make it title-case

df["Customer Name"]=df["Customer Name"].str.title()

In [47]:
df

      Customer Name      Segment        Country
5   Brosina Hoffman     Consumer  United States
6   Brosina Hoffman     Consumer  United States
7   Brosina Hoffman     Consumer  United States
8   Brosina Hoffman     Consumer  United States
9   Brosina Hoffman     Consumer  United States
10  Brosina Hoffman     Consumer  United States
11  Brosina Hoffman     Consumer  United States
12     Andrew Allen     Consumer  United States
13     Irene Maddox     Consumer  United States
14    Harold Pawlan  Home Office  United States
15    Harold Pawlan  Home Office  United States

### ✨ Replace
> There are two types of replace in pandas
1. Replacement at row-level. (Outer)
2. Replacement of string in a cell. (Inner)

In [58]:
# suppose we have to simply replace Home Office to HO in segment

df["Segment"]=df["Segment"].replace("Home Office", "HO") # this will replace Home Office with HO and update the DataFrame

In [59]:
df

      Customer Name   Segment        Country
5   Brosina Hoffman  Consumer  United States
6   Brosina Hoffman  Consumer  United States
7   Brosina Hoffman  Consumer  United States
8   Brosina Hoffman  Consumer  United States
9   Brosina Hoffman  Consumer  United States
10  Brosina Hoffman  Consumer  United States
11  Brosina Hoffman  Consumer  United States
12     Andrew Allen  Consumer  United States
13     Irene Maddox  Consumer  United States
14    Harold Pawlan        HO  United States
15    Harold Pawlan        HO  United States

In [67]:
# Now wherever is 'o' in segment i want it to get it replaced by **.

df["Segment"]=df["Segment"].str.replace("o","**")

In [68]:
df

      Customer Name    Segment        Country
5   Brosina Hoffman  C**nsumer  United States
6   Brosina Hoffman  C**nsumer  United States
7   Brosina Hoffman  C**nsumer  United States
8   Brosina Hoffman  C**nsumer  United States
9   Brosina Hoffman  C**nsumer  United States
10  Brosina Hoffman  C**nsumer  United States
11  Brosina Hoffman  C**nsumer  United States
12     Andrew Allen  C**nsumer  United States
13     Irene Maddox  C**nsumer  United States
14    Harold Pawlan         HO  United States
15    Harold Pawlan         HO  United States

In [71]:
# now if we just want first 3 chars of the name
# we can slice it using the .str

df["F3_Chars"]=df["Customer Name"].str[:3]

In [72]:
df

      Customer Name    Segment        Country F3_Chars
5   Brosina Hoffman  C**nsumer  United States      Bro
6   Brosina Hoffman  C**nsumer  United States      Bro
7   Brosina Hoffman  C**nsumer  United States      Bro
8   Brosina Hoffman  C**nsumer  United States      Bro
9   Brosina Hoffman  C**nsumer  United States      Bro
10  Brosina Hoffman  C**nsumer  United States      Bro
11  Brosina Hoffman  C**nsumer  United States      Bro
12     Andrew Allen  C**nsumer  United States      And
13     Irene Maddox  C**nsumer  United States      Ire
14    Harold Pawlan         HO  United States      Har
15    Harold Pawlan         HO  United States      Har

In [73]:
# suppose we want last 3 characters of the Customer Name

df["L3"]=df["Customer Name"].str[-3:]

In [74]:
df

      Customer Name    Segment        Country F3_Chars   L3
5   Brosina Hoffman  C**nsumer  United States      Bro  man
6   Brosina Hoffman  C**nsumer  United States      Bro  man
7   Brosina Hoffman  C**nsumer  United States      Bro  man
8   Brosina Hoffman  C**nsumer  United States      Bro  man
9   Brosina Hoffman  C**nsumer  United States      Bro  man
10  Brosina Hoffman  C**nsumer  United States      Bro  man
11  Brosina Hoffman  C**nsumer  United States      Bro  man
12     Andrew Allen  C**nsumer  United States      And  len
13     Irene Maddox  C**nsumer  United States      Ire  dox
14    Harold Pawlan         HO  United States      Har  lan
15    Harold Pawlan         HO  United States      Har  lan

In [80]:
ndf=(df["Customer Name"].str.split(expand=True))

In [81]:
ndf.columns=["First", "Last"]

In [82]:
ndf

      First     Last
5   Brosina  Hoffman
6   Brosina  Hoffman
7   Brosina  Hoffman
8   Brosina  Hoffman
9   Brosina  Hoffman
10  Brosina  Hoffman
11  Brosina  Hoffman
12   Andrew    Allen
13    Irene   Maddox
14   Harold   Pawlan
15   Harold   Pawlan

In [84]:
df=df.join(ndf)

In [85]:
df

      Customer Name    Segment        Country F3_Chars   L3    First     Last
5   Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
6   Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
7   Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
8   Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
9   Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
10  Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
11  Brosina Hoffman  C**nsumer  United States      Bro  man  Brosina  Hoffman
12     Andrew Allen  C**nsumer  United States      And  len   Andrew    Allen
13     Irene Maddox  C**nsumer  United States      Ire  dox    Irene   Maddox
14    Harold Pawlan         HO  United States      Har  lan   Harold   Pawlan
15    Harold Pawlan         HO  United States      Har  lan   Harold   Pawlan

### 📚 Filtering through string methods

In [86]:
df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Sample - Superstore.xls")

In [87]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [88]:
df=df.loc[5:15,["Customer Name", "Segment", "City"]]

In [89]:
df

      Customer Name      Segment         City
5   Brosina Hoffman     Consumer  Los Angeles
6   Brosina Hoffman     Consumer  Los Angeles
7   Brosina Hoffman     Consumer  Los Angeles
8   Brosina Hoffman     Consumer  Los Angeles
9   Brosina Hoffman     Consumer  Los Angeles
10  Brosina Hoffman     Consumer  Los Angeles
11  Brosina Hoffman     Consumer  Los Angeles
12     Andrew Allen     Consumer      Concord
13     Irene Maddox     Consumer      Seattle
14    Harold Pawlan  Home Office   Fort Worth
15    Harold Pawlan  Home Office   Fort Worth

In [92]:
# suppose we want only those records of customers who's name starts with letter 'I'

df[df["Customer Name"].str.startswith('I')]

   Customer Name   Segment     City
13  Irene Maddox  Consumer  Seattle

In [93]:
df[df["Customer Name"].str.endswith('n')]

      Customer Name      Segment         City
5   Brosina Hoffman     Consumer  Los Angeles
6   Brosina Hoffman     Consumer  Los Angeles
7   Brosina Hoffman     Consumer  Los Angeles
8   Brosina Hoffman     Consumer  Los Angeles
9   Brosina Hoffman     Consumer  Los Angeles
10  Brosina Hoffman     Consumer  Los Angeles
11  Brosina Hoffman     Consumer  Los Angeles
12     Andrew Allen     Consumer      Concord
14    Harold Pawlan  Home Office   Fort Worth
15    Harold Pawlan  Home Office   Fort Worth