## 📚 Data Transformation
> It is the process of modifying and restructuring the data to prepare it for analysis. <br>
> It can also defined as changing the shape of DataFrame by using data transformation methods.

💡 Note:-
1. Slicing is not considered as data tranformation.
2. Just like in group by we are not changing the original DataFrame but do some tranformations, it is considered as Data Tranformation.

In [4]:
import pandas as pd
pd.options.display.max_columns=50

In [2]:
df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Sample - Superstore.xls")

In [5]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [17]:
rows, cols = df.shape # it is an attribute not a method

print("No. of rows: ", rows)
print("No. of cols: ", cols)

No. of rows:  9994
No. of cols:  21

In [8]:
df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [18]:
x=df.groupby("Category").agg({"Sales": "sum"}) # with group by we have to use agg with it.

In [11]:
x

                       Sales
Category
Furniture        741999.7953
Office Supplies  719047.0320
Technology       836154.0330

In [12]:
x.reset_index(inplace=True)

In [13]:
x

          Category        Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [14]:
x=df.groupby(["Category", "Sub-Category"]).agg({"Sales": "sum"})

In [15]:
x.reset_index(inplace=True)

In [16]:
x

           Category Sub-Category        Sales
0         Furniture    Bookcases  114879.9963
1         Furniture       Chairs  328449.1030
2         Furniture  Furnishings   91705.1640
3         Furniture       Tables  206965.5320
4   Office Supplies   Appliances  107532.1610
5   Office Supplies          Art   27118.7920
6   Office Supplies      Binders  203412.7330
7   Office Supplies    Envelopes   16476.4020
8   Office Supplies    Fasteners    3024.2800
9   Office Supplies       Labels   12486.3120
10  Office Supplies        Paper   78479.2060
11  Office Supplies      Storage  223843.6080
12  Office Supplies     Supplies   46673.5380
13       Technology  Accessories  167380.3180
14       Technology      Copiers  149528.0300
15       Technology     Machines  189238.6310
16       Technology       Phones  330007.0540

In [19]:
# in group by we can also aggregate multiple columns with multiple aggregations.

x=df.groupby(["Category", "Sub-Category"]).agg({"Sales": "sum", "Profit": "sum", "Quantity": "sum"})
x.reset_index(inplace=True)
x

           Category Sub-Category        Sales      Profit  Quantity
0         Furniture    Bookcases  114879.9963  -3472.5560       868
1         Furniture       Chairs  328449.1030  26590.1663      2356
2         Furniture  Furnishings   91705.1640  13059.1436      3563
3         Furniture       Tables  206965.5320 -17725.4811      1241
4   Office Supplies   Appliances  107532.1610  18138.0054      1729
5   Office Supplies          Art   27118.7920   6527.7870      3000
6   Office Supplies      Binders  203412.7330  30221.7633      5974
7   Office Supplies    Envelopes   16476.4020   6964.1767       906
8   Office Supplies    Fasteners    3024.2800    949.5182       914
9   Office Supplies       Labels   12486.3120   5546.2540      1400
10  Office Supplies        Paper   78479.2060  34053.5693      5178
11  Office Supplies      Storage  223843.6080  21278.8264      3158
12  Office Supplies     Supplies   46673.5380  -1189.0995       647
13       Technology  Accessories  167380.3180  41936.6357      2976
14       Technology      Copiers  149528.0300  55617.8249       234
15       Technology     Machines  189238.6310   3384.7569       440
16       Technology       Phones  330007.0540  44515.7306      3289

### 📚 Pivot Table

> Primarily pivot tables are used to summarize the large dataset into two-dimensional cleaner format.

In [20]:
x=df.groupby(["Category", "Sub-Category", "Region"]).agg({"Sales": "sum"})
x.reset_index(inplace=True)
x

      Category Sub-Category   Region        Sales
0    Furniture    Bookcases  Central   24157.1768
1    Furniture    Bookcases     East   43819.3340
2    Furniture    Bookcases    South   10899.3620
3    Furniture    Bookcases     West   36004.1235
4    Furniture       Chairs  Central   85230.6460
..         ...          ...      ...          ...
63  Technology     Machines     West   42444.1220
64  Technology       Phones  Central   72403.2820
65  Technology       Phones     East  100614.9820
66  Technology       Phones    South   58304.4380
67  Technology       Phones     West   98684.3520

[68 rows x 4 columns]

In [22]:
# now suppose we have to create pivot for the above mentioned df
# for this we can use pivot_table() method, which is the pandas method

x=pd.pivot_table(data=df, index=["Category", "Sub-Category"], columns="Region", values="Sales", aggfunc="sum")

In [24]:
x.reset_index(inplace=True)

In [25]:
x

Region,Category,Sub-Category,Central,East,South,West
0,Furniture,Bookcases,24157.1768,43819.334,10899.362,36004.1235
1,Furniture,Chairs,85230.6460,96260.683,45176.446,101781.3280
2,Furniture,Furnishings,15254.3700,29071.380,17306.684,30072.7300
3,Furniture,Tables,39154.9710,39139.807,43916.192,84754.5620
4,Office Supplies,Appliances,23582.0330,34188.466,19525.326,30236.3360
5,Office Supplies,Art,5765.3400,7485.764,4655.622,9212.0660
6,Office Supplies,Binders,56923.2820,53497.997,37030.341,55961.1130
7,Office Supplies,Envelopes,4636.8720,4375.874,3345.556,4118.1000
8,Office Supplies,Fasteners,778.0300,819.718,503.316,923.2160
9,Office Supplies,Labels,2451.4720,2602.934,2353.180,5078.7260
10,Office Supplies,Paper,17491.9020,20172.602,14150.984,26663.7180
11,Office Supplies,Storage,45930.1120,71612.584,35768.060,70532.8520
12,Office Supplies,Supplies,9467.3720,10760.116,8318.928,18127.1220
13,Technology,Accessories,33956.0760,45033.372,27276.754,61114.1160
14,Technology,Copiers,37259.5700,53219.462,9299.756,49749.2420
15,Technology,Machines,26797.3840,66106.165,53890.960,42444.1220
16,Technology,Phones,72403.2820,100614.982,58304.438,98684.3520

In [26]:
x.columns.name=None

In [27]:
x

,Category,Sub-Category,Central,East,South,West
0,Furniture,Bookcases,24157.1768,43819.334,10899.362,36004.1235
1,Furniture,Chairs,85230.6460,96260.683,45176.446,101781.3280
2,Furniture,Furnishings,15254.3700,29071.380,17306.684,30072.7300
3,Furniture,Tables,39154.9710,39139.807,43916.192,84754.5620
4,Office Supplies,Appliances,23582.0330,34188.466,19525.326,30236.3360
5,Office Supplies,Art,5765.3400,7485.764,4655.622,9212.0660
6,Office Supplies,Binders,56923.2820,53497.997,37030.341,55961.1130
7,Office Supplies,Envelopes,4636.8720,4375.874,3345.556,4118.1000
8,Office Supplies,Fasteners,778.0300,819.718,503.316,923.2160
9,Office Supplies,Labels,2451.4720,2602.934,2353.180,5078.7260
10,Office Supplies,Paper,17491.9020,20172.602,14150.984,26663.7180
11,Office Supplies,Storage,45930.1120,71612.584,35768.060,70532.8520
12,Office Supplies,Supplies,9467.3720,10760.116,8318.928,18127.1220
13,Technology,Accessories,33956.0760,45033.372,27276.754,61114.1160
14,Technology,Copiers,37259.5700,53219.462,9299.756,49749.2420
15,Technology,Machines,26797.3840,66106.165,53890.960,42444.1220
16,Technology,Phones,72403.2820,100614.982,58304.438,98684.3520

In [30]:
x.T # to transpose simply use capital T or transpose method

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
Category,Furniture,Furniture,Furniture,Furniture,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Technology,Technology,Technology,Technology
Sub-Category,Bookcases,Chairs,Furnishings,Tables,Appliances,Art,Binders,Envelopes,Fasteners,Labels,Paper,Storage,Supplies,Accessories,Copiers,Machines,Phones
Central,24157.1768,85230.646,15254.37,39154.971,23582.033,5765.34,56923.282,4636.872,778.03,2451.472,17491.902,45930.112,9467.372,33956.076,37259.57,26797.384,72403.282
East,43819.334,96260.683,29071.38,39139.807,34188.466,7485.764,53497.997,4375.874,819.718,2602.934,20172.602,71612.584,10760.116,45033.372,53219.462,66106.165,100614.982
South,10899.362,45176.446,17306.684,43916.192,19525.326,4655.622,37030.341,3345.556,503.316,2353.18,14150.984,35768.06,8318.928,27276.754,9299.756,53890.96,58304.438
West,36004.1235,101781.328,30072.73,84754.562,30236.336,9212.066,55961.113,4118.1,923.216,5078.726,26663.718,70532.852,18127.122,61114.116,49749.242,42444.122,98684.352

In [31]:
x.transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
Category,Furniture,Furniture,Furniture,Furniture,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Technology,Technology,Technology,Technology
Sub-Category,Bookcases,Chairs,Furnishings,Tables,Appliances,Art,Binders,Envelopes,Fasteners,Labels,Paper,Storage,Supplies,Accessories,Copiers,Machines,Phones
Central,24157.1768,85230.646,15254.37,39154.971,23582.033,5765.34,56923.282,4636.872,778.03,2451.472,17491.902,45930.112,9467.372,33956.076,37259.57,26797.384,72403.282
East,43819.334,96260.683,29071.38,39139.807,34188.466,7485.764,53497.997,4375.874,819.718,2602.934,20172.602,71612.584,10760.116,45033.372,53219.462,66106.165,100614.982
South,10899.362,45176.446,17306.684,43916.192,19525.326,4655.622,37030.341,3345.556,503.316,2353.18,14150.984,35768.06,8318.928,27276.754,9299.756,53890.96,58304.438
West,36004.1235,101781.328,30072.73,84754.562,30236.336,9212.066,55961.113,4118.1,923.216,5078.726,26663.718,70532.852,18127.122,61114.116,49749.242,42444.122,98684.352

In [40]:
x=df.groupby(["Category", "Sub-Category"]).agg({"Sales": "sum"})
x.reset_index(inplace=True)

In [41]:
x

           Category Sub-Category        Sales
0         Furniture    Bookcases  114879.9963
1         Furniture       Chairs  328449.1030
2         Furniture  Furnishings   91705.1640
3         Furniture       Tables  206965.5320
4   Office Supplies   Appliances  107532.1610
5   Office Supplies          Art   27118.7920
6   Office Supplies      Binders  203412.7330
7   Office Supplies    Envelopes   16476.4020
8   Office Supplies    Fasteners    3024.2800
9   Office Supplies       Labels   12486.3120
10  Office Supplies        Paper   78479.2060
11  Office Supplies      Storage  223843.6080
12  Office Supplies     Supplies   46673.5380
13       Technology  Accessories  167380.3180
14       Technology      Copiers  149528.0300
15       Technology     Machines  189238.6310
16       Technology       Phones  330007.0540

In [55]:
# similar to lead() function in sql and if we need to calculate YoY or MoM, for this we can use shift(n) method

x["diff"]=x["Sales"]-x["Sales"].shift(1)

In [56]:
x

           Category Sub-Category        Sales         diff
0         Furniture    Bookcases  114879.9963          NaN
1         Furniture       Chairs  328449.1030  213569.1067
2         Furniture  Furnishings   91705.1640 -236743.9390
3         Furniture       Tables  206965.5320  115260.3680
4   Office Supplies   Appliances  107532.1610  -99433.3710
5   Office Supplies          Art   27118.7920  -80413.3690
6   Office Supplies      Binders  203412.7330  176293.9410
7   Office Supplies    Envelopes   16476.4020 -186936.3310
8   Office Supplies    Fasteners    3024.2800  -13452.1220
9   Office Supplies       Labels   12486.3120    9462.0320
10  Office Supplies        Paper   78479.2060   65992.8940
11  Office Supplies      Storage  223843.6080  145364.4020
12  Office Supplies     Supplies   46673.5380 -177170.0700
13       Technology  Accessories  167380.3180  120706.7800
14       Technology      Copiers  149528.0300  -17852.2880
15       Technology     Machines  189238.6310   39710.6010
16       Technology       Phones  330007.0540  140768.4230

### 📚 Data Consolidation
> It is the process of combining two or more DataFrames or Series to make it unified DataFrame.

In [61]:
df1=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Consolidation\Jan-2024.xlsx")

In [62]:
df1["Months"]="Jan"

In [63]:
df1

     Name  Sales Months
0   Mohit     70    Jan
1  Subham     53    Jan
2  Mayank     96    Jan
3   Gopal     29    Jan
4   Suman     13    Jan
5  Subham     80    Jan
6   Rohan     30    Jan
7   Kamal     89    Jan
8  Vishal     89    Jan
9   Karan     83    Jan

In [64]:
df2=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Consolidation\Feb-2024.xlsx")
df2["Months"]="Feb"

In [65]:
df2

     Name  Sales Months
0   Mohit     70    Feb
1  Subham     53    Feb
2  Mayank     96    Feb
3   Gopal     29    Feb
4   Suman     13    Feb
5  Subham     80    Feb
6   Rohan     30    Feb
7   Kamal     89    Feb
8  Vishal     89    Feb
9   Karan     83    Feb

In [68]:
# concat() is the pandas method for combining two or more Dataframes row-wise or column-wise

df=pd.concat([df1,df2], ignore_index=True)

In [69]:
df

      Name  Sales Months
0    Mohit     70    Jan
1   Subham     53    Jan
2   Mayank     96    Jan
3    Gopal     29    Jan
4    Suman     13    Jan
5   Subham     80    Jan
6    Rohan     30    Jan
7    Kamal     89    Jan
8   Vishal     89    Jan
9    Karan     83    Jan
10   Mohit     70    Feb
11  Subham     53    Feb
12  Mayank     96    Feb
13   Gopal     29    Feb
14   Suman     13    Feb
15  Subham     80    Feb
16   Rohan     30    Feb
17   Kamal     89    Feb
18  Vishal     89    Feb
19   Karan     83    Feb

In [70]:
import os

In [76]:
path=r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Consolidation"
file_list=os.listdir(path)
df=pd.DataFrame()
for i in file_list:
    final_path=os.path.join(path,i)
    df1=pd.read_excel(final_path)
    df1["Month"]=i.strip(".xlsx")
    df=pd.concat([df,df1], ignore_index=True)

In [77]:
df

      Name  Sales     Month
0    Mohit     70  Apr-2024
1   Subham     53  Apr-2024
2   Mayank     96  Apr-2024
3    Gopal     29  Apr-2024
4    Suman     13  Apr-2024
5   Subham     80  Apr-2024
6    Rohan     30  Apr-2024
7    Kamal     89  Apr-2024
8   Vishal     89  Apr-2024
9    Karan     83  Apr-2024
10   Mohit     70  Feb-2024
11  Subham     53  Feb-2024
12  Mayank     96  Feb-2024
13   Gopal     29  Feb-2024
14   Suman     13  Feb-2024
15  Subham     80  Feb-2024
16   Rohan     30  Feb-2024
17   Kamal     89  Feb-2024
18  Vishal     89  Feb-2024
19   Karan     83  Feb-2024
20   Mohit     70  Jan-2024
21  Subham     53  Jan-2024
22  Mayank     96  Jan-2024
23   Gopal     29  Jan-2024
24   Suman     13  Jan-2024
25  Subham     80  Jan-2024
26   Rohan     30  Jan-2024
27   Kamal     89  Jan-2024
28  Vishal     89  Jan-2024
29   Karan     83  Jan-2024
30   Mohit     70  Mar-2024
31  Subham     53  Mar-2024
32  Mayank     96  Mar-2024
33   Gopal     29  Mar-2024
34   Suman     13  Mar-2024
35  Subham     80  Mar-2024
36   Rohan     30  Mar-2024
37   Kamal     89  Mar-2024
38  Vishal     89  Mar-2024
39   Karan     83  Mar-2024