In [1]:
import pandas as pd

In [65]:
# generally when we import excel workbook it generally fetches correct data types of the columns unlike the csv or text format files.

df=pd.read_excel(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Sample - Superstore.xls")

In [4]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [70]:
# but in the csv format we have to convert the data types according to our requirements
# date generally comes in str format

df=pd.read_csv(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Sample - Superstore-Orders.csv")

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [72]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [73]:
# pandas have to_datetime() to convert string to datetime format

df["Order Date"]=pd.to_datetime(df["Order Date"], format="%m/%d/%Y")

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(3), str(14)
memory usage: 1.6 MB

In [75]:
df["Ship Date"]=pd.to_datetime(df["Ship Date"], format="%m/%d/%Y")

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [77]:
df=df.loc[:,["Order Date", "Ship Date", "Sales", "Profit"]]

In [78]:
df.head(3)

  Order Date  Ship Date   Sales    Profit
0 2016-11-08 2016-11-11  261.96   41.9136
1 2016-11-08 2016-11-11  731.94  219.5820
2 2016-06-12 2016-06-16   14.62    6.8714

In [79]:
# now suppose if we want separate columns for the year, day and month
# year, month, day
df["Year"]=df["Order Date"].dt.year
df["Month"]=df["Order Date"].dt.month
df["Day"]=df["Order Date"].dt.day

In [80]:
df.head()

  Order Date  Ship Date     Sales    Profit  Year  Month  Day
0 2016-11-08 2016-11-11  261.9600   41.9136  2016     11    8
1 2016-11-08 2016-11-11  731.9400  219.5820  2016     11    8
2 2016-06-12 2016-06-16   14.6200    6.8714  2016      6   12
3 2015-10-11 2015-10-18  957.5775 -383.0310  2015     10   11
4 2015-10-11 2015-10-18   22.3680    2.5164  2015     10   11

In [81]:
# now suppose we want to add month and day name column as well
df["Month_name"]=df["Order Date"].dt.month_name()
df["Day_name"]=df["Order Date"].dt.day_name()

In [82]:
df.head()

,Order Date,Ship Date,Sales,Profit,Year,Month,Day,Month_name,Day_name
0,2016-11-08,2016-11-11,261.9600,41.9136,2016,11,8,November,Tuesday
1,2016-11-08,2016-11-11,731.9400,219.5820,2016,11,8,November,Tuesday
2,2016-06-12,2016-06-16,14.6200,6.8714,2016,6,12,June,Sunday
3,2015-10-11,2015-10-18,957.5775,-383.0310,2015,10,11,October,Sunday
4,2015-10-11,2015-10-18,22.3680,2.5164,2015,10,11,October,Sunday

In [83]:
df["Quarter"]=df["Order Date"].dt.quarter

In [84]:
df.head()

,Order Date,Ship Date,Sales,Profit,Year,Month,Day,Month_name,Day_name,Quarter
0,2016-11-08,2016-11-11,261.9600,41.9136,2016,11,8,November,Tuesday,4
1,2016-11-08,2016-11-11,731.9400,219.5820,2016,11,8,November,Tuesday,4
2,2016-06-12,2016-06-16,14.6200,6.8714,2016,6,12,June,Sunday,2
3,2015-10-11,2015-10-18,957.5775,-383.0310,2015,10,11,October,Sunday,4
4,2015-10-11,2015-10-18,22.3680,2.5164,2015,10,11,October,Sunday,4

In [85]:
df.drop(columns="Period", inplace=True)

KeyError: "['Period'] not found in axis"

In [ ]:
df.head()

#### 💡 Datetime in pandas most commonly used attribute and method are as follows:-
1. year
2. month
3. day
4. day_name()
5. month_name()
6. hour
7. time
8. quarter

In [ ]:
# if we want to convert any datetie format to string format then use strftime(format='') method

df["Ship Date1"]=df["Ship Date"].dt.strftime('%d-%m-%Y')

In [86]:
df.head()

,Order Date,Ship Date,Sales,Profit,Year,Month,Day,Month_name,Day_name,Quarter
0,2016-11-08,2016-11-11,261.9600,41.9136,2016,11,8,November,Tuesday,4
1,2016-11-08,2016-11-11,731.9400,219.5820,2016,11,8,November,Tuesday,4
2,2016-06-12,2016-06-16,14.6200,6.8714,2016,6,12,June,Sunday,2
3,2015-10-11,2015-10-18,957.5775,-383.0310,2015,10,11,October,Sunday,4
4,2015-10-11,2015-10-18,22.3680,2.5164,2015,10,11,October,Sunday,4

In [87]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  9994 non-null   datetime64[us]
 1   Ship Date   9994 non-null   datetime64[us]
 2   Sales       9994 non-null   float64
 3   Profit      9994 non-null   float64
 4   Year        9994 non-null   int32
 5   Month       9994 non-null   int32
 6   Day         9994 non-null   int32
 7   Month_name  9994 non-null   str
 8   Day_name    9994 non-null   str
 9   Quarter     9994 non-null   int32
dtypes: datetime64[us](2), float64(2), int32(4), str(2)
memory usage: 624.8 KB

>➡️ As you can see here **Ship Date1** is having string datatype.

### 📚 Filtering DataFrame on the basis of datetime

In [89]:
df=df.iloc[:,:4]

In [90]:
df.head()

  Order Date  Ship Date     Sales    Profit
0 2016-11-08 2016-11-11  261.9600   41.9136
1 2016-11-08 2016-11-11  731.9400  219.5820
2 2016-06-12 2016-06-16   14.6200    6.8714
3 2015-10-11 2015-10-18  957.5775 -383.0310
4 2015-10-11 2015-10-18   22.3680    2.5164

In [91]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  9994 non-null   datetime64[us]
 1   Ship Date   9994 non-null   datetime64[us]
 2   Sales       9994 non-null   float64
 3   Profit      9994 non-null   float64
dtypes: datetime64[us](2), float64(2)
memory usage: 312.4 KB

In [98]:
df[df["Ship Date"]<=pd.Timestamp('2015-12-31')].head() # we use pd.Timestamp('Date')

  Order Date  Ship Date     Sales    Profit
3 2015-10-11 2015-10-18  957.5775 -383.0310
4 2015-10-11 2015-10-18   22.3680    2.5164
5 2014-06-09 2014-06-14   48.8600   14.1694
6 2014-06-09 2014-06-14    7.2800    1.9656
7 2014-06-09 2014-06-14  907.1520   90.7152

In [99]:
pd.Timestamp.today().date()

datetime.date(2026, 10, 26)

In [100]:
pd.Timestamp.today().time()

datetime.time(12, 50, 58, 505910)

In [101]:
# to add or remove days, hours, mins etc. we use pd.Timedelta(days=5)
# now suppose we wanted to add 5 days to the current ship date to generate new ship date

df["New Ship Date"]=df["Ship Date"] + pd.Timedelta(days=5)

In [102]:
df.head()

  Order Date  Ship Date     Sales    Profit New Ship Date
0 2016-11-08 2016-11-11  261.9600   41.9136    2016-11-16
1 2016-11-08 2016-11-11  731.9400  219.5820    2016-11-16
2 2016-06-12 2016-06-16   14.6200    6.8714    2016-06-21
3 2015-10-11 2015-10-18  957.5775 -383.0310    2015-10-23
4 2015-10-11 2015-10-18   22.3680    2.5164    2015-10-23

> Here pd.Timedelta(days=5) added 5 days to the new ship date.

➡️ In the same way we can make subtract 5 days from the date.

In [103]:
df["New Ship Date2"]=df["Ship Date"]-pd.Timedelta(days=5)

In [104]:
df.head()

  Order Date  Ship Date     Sales    Profit New Ship Date New Ship Date2
0 2016-11-08 2016-11-11  261.9600   41.9136    2016-11-16     2016-11-06
1 2016-11-08 2016-11-11  731.9400  219.5820    2016-11-16     2016-11-06
2 2016-06-12 2016-06-16   14.6200    6.8714    2016-06-21     2016-06-11
3 2015-10-11 2015-10-18  957.5775 -383.0310    2015-10-23     2015-10-13
4 2015-10-11 2015-10-18   22.3680    2.5164    2015-10-23     2015-10-13

In [105]:
# suppose we want the difference between the order date and the ship date.
# we can simply subtract both of them

df["Date Diff"]=df["Ship Date"]-df["Order Date"]

In [106]:
df.head()

,Order Date,Ship Date,Sales,Profit,New Ship Date,New Ship Date2,Date Diff
0,2016-11-08,2016-11-11,261.9600,41.9136,2016-11-16,2016-11-06,3 days
1,2016-11-08,2016-11-11,731.9400,219.5820,2016-11-16,2016-11-06,3 days
2,2016-06-12,2016-06-16,14.6200,6.8714,2016-06-21,2016-06-11,4 days
3,2015-10-11,2015-10-18,957.5775,-383.0310,2015-10-23,2015-10-13,7 days
4,2015-10-11,2015-10-18,22.3680,2.5164,2015-10-23,2015-10-13,7 days

In [109]:
df=df.iloc[:,1:4]

In [111]:
df.head()

   Ship Date     Sales    Profit
0 2016-11-11  261.9600   41.9136
1 2016-11-11  731.9400  219.5820
2 2016-06-16   14.6200    6.8714
3 2015-10-18  957.5775 -383.0310
4 2015-10-18   22.3680    2.5164

➡️ Suppose we need sales and profit sum per day
> for that we can use groupby

In [113]:
df.groupby(by="Ship Date").agg({"Sales": "sum", "Profit": "sum"}).reset_index().head()

   Ship Date     Sales     Profit
0 2014-01-07    29.228    10.7910
1 2014-01-08   307.500   -56.6589
2 2014-01-10  4374.880  1343.4814
3 2014-01-12   106.694   -67.0781
4 2014-01-13    40.544    10.9180

In [114]:
df[df["Ship Date"]==pd.Timestamp('2014-01-07')]

      Ship Date   Sales  Profit
7180 2014-01-07  12.780  5.2398
7980 2014-01-07  16.448  5.5512

> as we can see here the sum of 2014-01-07 is the same when we are applying the groupby.

### ➡️ Sum for every 5th day, not the rolling sum
> so it will calculate the sum of values current date with the next 4days in that row and reduce it to that date.

In [116]:
# step-1: to change the index to date

df=df.loc[:,["Ship Date", "Profit"]]

In [117]:
df.head()

   Ship Date    Profit
0 2016-11-11   41.9136
1 2016-11-11  219.5820
2 2016-06-16    6.8714
3 2015-10-18 -383.0310
4 2015-10-18    2.5164

In [122]:
df=df.set_index("Ship Date")

In [128]:
# to calculate sum for every 5 days we use resample method

df["Profit"].resample("5D").sum().reset_index() # here it is giving sum on every 5th day

     Ship Date     Profit
0   2014-01-07  1297.6135
1   2014-01-12   330.2070
2   2014-01-17    38.2543
3   2014-01-22   588.4723
4   2014-01-27   169.5654
..         ...        ...
287 2017-12-12  -136.2901
288 2017-12-17  1030.2416
289 2017-12-22  3176.9469
290 2017-12-27  1556.9625
291 2018-01-01   934.7894

[292 rows x 2 columns]

In [129]:
df["Profit"].resample("YE").sum().reset_index() # here it is giving yearly profit

   Ship Date      Profit
0 2014-12-31  47292.7255
1 2015-12-31  62881.5299
2 2016-12-31  82941.1017
3 2017-12-31  92346.8752
4 2018-12-31    934.7894

### ➡️ Rolling average of every 3rd day, which means current and previous 2
> for this we have to use rolling(window=3) with the mean method.

In [131]:
df.reset_index(inplace=True)

In [133]:
df.head()

   Ship Date    Profit
0 2016-11-11   41.9136
1 2016-11-11  219.5820
2 2016-06-16    6.8714
3 2015-10-18 -383.0310
4 2015-10-18    2.5164

In [134]:
df["Rolling Profit"]=df["Profit"].rolling(window=3).mean()

In [135]:
df.head(10)

   Ship Date    Profit  Rolling Profit
0 2016-11-11   41.9136             NaN
1 2016-11-11  219.5820             NaN
2 2016-06-16    6.8714       89.455667
3 2015-10-18 -383.0310      -52.192533
4 2015-10-18    2.5164     -124.547733
5 2014-06-14   14.1694     -122.115067
6 2014-06-14    1.9656        6.217133
7 2014-06-14   90.7152       35.616733
8 2014-06-14    5.7825       32.821100
9 2014-06-14   34.4700       43.655900